### ISSUE TITLE
Attribution page link broken

### ISSUE THREAD

**Issue by qubist** [h-be/acorn-docs#8]
In README.md, the link to the attribution file in this line

> Please consult [our ATTRIBUTION file] for full details including other images, code, and prior work.

goes to `https://github.com/h-be/acorn-docs/ATTRIBUTION.md` which shows "Not Found" for me. Instead I believe it should go to `https://github.com/h-be/acorn-docs/blob/master/ATTRIBUTION.md`.

**Comment by Connoropolous** [comment]
thanks!
